name: Test pip and conda install
runs:
  using: composite
  steps:
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"
  - name: Create requirements.txt file
    shell: bash
    run: |
      rm -r requirements.txt
      python3 -m pip install .[dev]
      python3 -m pip-compile --no-emit-options
  - name: Build a binary wheel and a source tarball
    shell: bash
    run: python3 -m build
  - name: Install package via pip
    shell: bash
    run: pip install dist/*.whl
  - name: Test pip installed version with unittest
    shell: bash
    run: python3 -m unittest discover
  - name: Install conda environment
    shell: bash
    run: $CONDA/bin/conda env update --name base --file=environment.yml
  - name: Test Conda installed version with unittest
    shell: bash
    run: $CONDA/bin/python3 -m unittest discover
