name: Test pip and conda install
runs:
  using: composite
  steps:
  - name: Set up Python 3.12
    uses: actions/setup-python@v6
    with:
      python-version: "3.12"
  - name: Configure git for private repo access
    shell: bash
    run: git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
    env:
      GITHUB_TOKEN: ${{ github.token }}
  - name: Install package via pip
    shell: bash
    run: python3 -m pip install .
  - name: Test pip installed version with unittest
    shell: bash
    run: python3 -m unittest discover
  - name: Install conda environment
    shell: bash
    run: $CONDA/bin/conda env update --name base --file=environment.yml
  - name: Test Conda installed version with unittest
    shell: bash
    run: $CONDA/bin/python3 -m unittest discover
