name: Test pip and conda install
runs:
  using: composite
  steps:
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"
  - name: Create requirements.txt file
    shell: bash
    run: |
      python3 -m pip install .[dev]
      python3 -m piptools compile --no-emit-options
  - name: Build a binary wheel and a source tarball
    shell: bash
    run: python3 -m build
  - name: Install package via pip
    shell: bash
    run: pip install dist/*.whl
  - name: Test pip installed version with unittest
    shell: bash
    run: python3 -m unittest discover
  - name: Build a conda package
    shell: bash
    run: |
      $CONDA/bin/conda install --channel=conda-forge conda-build
      $CONDA/bin/conda build . --output-folder ./conda
  - name: Install build in conda base environment
    shell: bash
    run: $CONDA/bin/conda install ./conda/noarch/*.conda
  - name: Test Conda installed version with unittest
    shell: bash
    run: $CONDA/bin/python3 -m unittest discover
