name: Test
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"
  - name: Create requirements.txt file
    run: |
      python3 -m pip install .[dev]
      pip-compile
  - name: Install package via pip
    run: |
      python3 -m pip install .
  - name: Test pip installed version with unittest
    run: |
      python3 -m unittest discover
  - name: Install package via conda
    run: |
      $CONDA/bin/conda env update --file environment.yml --name base
  - name: Test Conda installed version with unittest
    run: |
      $CONDA/bin/python3 -m unittest discover
