name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/reusable/install_and_test
        with:
          private_repo_token: ${{ secrets.NDEA_INTERNAL_REPO_TOKEN }}
