name: Test

on:
  workflow_call:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Confirm requirements.txt is up to date. (If not you should run "pip-compile").
      run: |
        mv requirements.txt requirements.txt.committed
        python3 -m pip install .[dev]
        pip-compile
        diff requirements.txt requirements.txt.committed  # Nonzero exit code if not identical
    - name: Install package via pip
      run: |
        python3 -m pip install .
    - name: Test pip installed version with unittest
      run: |
        python3 -m unittest discover
    - name: Install package via conda
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Test Conda installed version with unittest
      run: |
        $CONDA/bin/python3 -m unittest discover