name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_requirements_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/reusable/setup
