name: Test pip install

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Confirm requirements.txt is up to date. (If not you should run "pip-compile").
      run: |
        mv requirements.txt requirements.txt.committed
        pip install .[dev]
        pip-compile
        diff requirements.txt requirements.txt.committed  # Nonzero exit code if not identical

    - name: Install package
      run: |
        python3 -m pip install .

    - name: Test with unittest
      run: |
        python3 -m unittest discover
